### ISSUE TITLE
Placeholders being stripped

### ISSUE THREAD

**Issue by dannyglover** [sxtfv/flutter_arb_translator#10]
For example this arb entry in English: `"welcomeTitle": "Welcome to {appTitle}",` becomes: `"welcomeTitle": "Bienvenidos a ",` in Spanish.

This happens whenever the placeholder is at the end of a string. Even adding an exclamation mark does not fix it, i.e.  `"welcomeTitle": "Welcome to {appTitle}!",`

Can this be looked into please?
Thank you

**Comment by sxtfv** [comment]
Hello @dannyglover I will check in 24 hours and reply

**Comment by sxtfv** [comment]
@dannyglover I just checked with the latest version of the package and it works
Please note that if you are using package which is older than 1.0.9 then it's required to specify annotation for each entry explicitly. See this article for more details https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization about Flutter ARB file structure

**Comment by dannyglover** [comment]
Hi.

I'm using version 1.0.13 and am using the Azure backend. 

And my command:

`dart run flutter_arb_translator:main --from en --to es --service azure`

**Comment by sxtfv** [comment]
@dannyglover 
Tried the same command and this is how my source app_en.arb file looks
```
{
  "welcomeTitle": "Welcome to {appTitle}"
}
```
and this is how generated translation (app_es.arb) looks:
```
{
  "welcomeTitle": "Bienvenidos a {appTitle}"
}
```
Please note that package does not re-translate entries by default. Try to delete "welcomeTitle" entry from the app_es.arb file or try to execute the translation command with `-o` flag

**Comment by dannyglover** [comment]
> @dannyglover 
> Tried the same command and this is how my source app_en.arb file looks
> ```
> {
>   "welcomeTitle": "Welcome to {appTitle}"
> }
> ```
> and this is how generated translation (app_es.arb) looks:
> ```
> {
>   "welcomeTitle": "Bienvenidos a {appTitle}"
> }
> ```
> Please note that package does not re-translate entries by default. Try to delete "welcomeTitle" entry from the app_es.arb file or try to execute the translation command with `-o` flag

Ah! I forgot about that :/ I added the `-o` flag to the start of the command and that fixed my issue.

Sorry for the false alarm and thank you for creating this great package.

Happy new year!

**Comment by sxtfv** [comment]
You are welcome. Happy new year 😄
