### ISSUE TITLE
Change Intl to Version 19 

### ISSUE THREAD

**Issue by FantaMagier** [sxtfv/flutter_arb_translator#11]
**In Flutter 3.22:**

Because flutter_arb_translator >=1.0.13 depends on intl ^0.18.0 and every version of flutter_localizations from sdk depends on intl 0.19.0, flutter_arb_translator >=1.0.13 is incompatible with flutter_localizations from sdk.
So, because histamin_scanner depends on both flutter_localizations from sdk and flutter_arb_translator ^1.0.13, version solving failed.

Can we update this?

**Comment by sxtfv** [comment]
@FantaMagier Thank you for your message. Currently I am on vacation and will update in the end of May

**Comment by FantaMagier** [comment]
@sxtfv  Should I do a PR?

**Comment by sxtfv** [comment]
You can do a PR but only I can publish a new version

**Comment by FantaMagier** [comment]
ok all right, then enjoy your vacation :D

**Comment by sxtfv** [comment]
@FantaMagier thank you. I will let you know once update is available

**Comment by sxtfv** [comment]
@FantaMagier I just published a new version 1.0.14 with updated dependencies

**Comment by FantaMagier** [comment]
@sxtfv Thanks Mate!
