### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by JohnWeidner** [sxtfv/flutter_arb_translator#2]
This sounds exactly like the service I am looking for.  Unfortunately, I could not figure out how to configure it properly.  I am trying to use this with Google Cloud Translate.  I created a service account and key at https://console.cloud.google.com/iam-admin/serviceaccounts.  However, it wasn't obvious what I was supposed to put in the flutter_arb_translator_config.json file as the value for the "PrivateKey".  I tried using the "Key" value listed on the KEYS tab for my service account.  I tried downloading the key file and copying the contents of that file to use as the PrivateKey.  And I tried copying the key file to the dev_assets folder and using the name of the file as the value for the PrivateKey.  However, when running `flutter pub run flutter_arb_translator:main --from en --to es --service google
` each time I got the following error:

 ERR: Failed to initialize translator service
FormatException: Unable to parse key, invalid format.

**Comment by JohnWeidner** [comment]
When I said I copied the content of the key file, that wasn't exactly right.  When I looked at the contents of the downloaded file, I saw it contained a "private_key" field, so I had tried copying and pasting that, which did NOT work.  However, when I copied and pasted the entire contents of the downloaded key file, that seems to be working.

**Comment by JohnWeidner** [comment]
Actually, copying the private_key value from the downloaded json key file and pasting that as the "PrivateKey" value in the flutter_arb_translator_config.json file is what seemed to work.

**Comment by sxtfv** [comment]
@JohnWeidner thank you for your message. Great that you figured it out on your own, I will update the documentation
