### ISSUE TITLE
DeepL translation does not work

### ISSUE THREAD

**Issue by slavap** [sxtfv/flutter_arb_translator#3]
According to the DeepL documentation https://www.deepl.com/docs-api
there has to be a header: Authorization: DeepL-Auth-Key [yourAuthKey] 
I don't see that anywhere in deepl service code.

**Comment by sxtfv** [comment]
Thank you for this note, I will push an update shortly

**Comment by slavap** [comment]
@sxtfv great, thank you!

**Comment by sxtfv** [comment]
@slavap I pushed an update (1.0.8). Please check

**Comment by slavap** [comment]
Yes, it works now with even DeepL free plan:
```json
{
  "DeepL": {
    "Url": "https://api-free.deepl.com",
    "ApiKey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:xx"
  }
}
```
Thank you for the quick fix.

**Comment by slavap** [comment]
done
