### ISSUE TITLE
Incorrect translation for plural messages

### ISSUE THREAD

**Issue by slavap** [sxtfv/flutter_arb_translator#4]
I'm not sure if anything can be done with that, but for the following string:

"numAdults": "{num, plural, one{1 Adult} other{{num} Adults}}" 

the German translation is:

"numAdults": "{num, plural, one{1 Erwachsener} other{{Anzahl} Erwachsene}}"

So {num} was erroneously replaced with {Anzahl} 
Can it be somehow suggested to a translator to ignore such parameters?

**Comment by sxtfv** [comment]
I will check

**Comment by slavap** [comment]
@sxtfv Theoretically, it could be implemented as "postprocessing" in flutter_arb_translator code.
I.e. if there were parameters in source language, the SAME number of parameters has to be in target message.

**Comment by sxtfv** [comment]
@slavap 
I just checked and translated this file
```
{
  "numAdults": "{num, plural, one{1 Adult} other{{num} Adults}}",
  "@numAdults" : {
    "placeholders": {
      "num": {}
    }
  }
}
```
to this
```
{
  "numAdults": "{num, plural, one{1 Erwachsener} other{{num} Erwachsene}}",
  "@numAdults": {
    "placeholders": {
      "num": {}
    }
  }
}
```
and this
```
{
  "numAdults": "{num, plural, one{1 Adulto} other{{num} Adulti}}",
  "@numAdults": {
    "placeholders": {
      "num": {}
    }
  }
}
```
using DeepL without issue. Please add annotation if you didn't
But If you did, please share the full ARB file entry

**Comment by slavap** [comment]
@sxtfv no, I did not add placeholders. And actually it is quite hard to add them to all messages. Can I define placeholders globally? E.g. declare {num} as placeholder for all messages where it occurs.

**Comment by sxtfv** [comment]
@slavap 
It's Flutter ARB file format https://docs.flutter.dev/ui/accessibility-and-localization/internationalization
You cannot define global placeholders

**Comment by slavap** [comment]
@sxtfv  I think adding this placeholder declaration just “tricks” DeepL somehow, doubt it is able to understand it. Also in my arb files I don’t declare any placeholders, because I’m using intl, which works perfectly fine without them. Also the interesting thing is that DeepL fails on German, but works fine for Spanish and Russian - for the same English arb source file.

**Comment by sxtfv** [comment]
I will consider automatic placeholder detection as a feature for this package

**Comment by sxtfv** [comment]
@slavap I will add this feature and let you know once update is published

**Comment by slavap** [comment]
@sxtfv perfect, thanks!

**Comment by sxtfv** [comment]
@slavap I just pushed an update - 1.0.9. Please check it
Please note that this package does not translate entries which were already translated. You will need to manually remove bad entries from target file or use `-o` flag which will update all translations

**Comment by slavap** [comment]
@sxtfv Thank you! In my tests it works just fine now.
