### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by veronikalaskova** [sxtfv/flutter_arb_translator#9]
Hi,
Just made a PR to add Amazon translate as another service option. 

I also have a suggestion for an improvement. 
Would it be possible to improve the translations to be a bit more smart regarding messages that already exist but have been updated? Aka instead of having to re-translate the whole .arb file, it would pick out the lines that need to have an updated translation.

Eg:
Previous version of .arb file
{
  "hello": "Hello world",
  "goodbye": "Goodbye",
}
New version of .arb file
{
  "hello": "Hello world, what a lovely day!",
  "goodbye": "Goodbye",
}
Line sent for translation: "hello": "Hello world, what a lovely day!"

It would be greate if it would pick out the hello line to re-translate. In the current version the modified messages were ignored. 
Cheers.

**Comment by sxtfv** [comment]
Hello, I just reviewed your PR, please check.
Currently, if you modified an entry you will need to delete it from already translated files. I will consider this feature for future releases, thank you for suggestion

**Comment by veronikalaskova** [comment]
Hi,
Thanks, that is great to know. 
I'm not sure if this workaround is documented somewhere and I've just missed it. Can confirm this works.

**Comment by sxtfv** [comment]
@veronikalaskova I just merged your PR. Will release an update today or on Monday

**Comment by sxtfv** [comment]
Hi @veronikalaskova, I just pushed the update

**Comment by sxtfv** [comment]
The suggestion is noted and will be considered for future releases. Currently you can handle editing by modifying entries in already translated files
Closing the issue
